# Generated by Django 4.2.2 on 2023-07-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORG_ID', models.IntegerField(null=True)),
                ('CLIENT_ID', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True, verbose_name='姓名')),
                ('gender', models.CharField(max_length=5, null=True, verbose_name='性别')),
                ('phone', models.CharField(max_length=50, null=True)),
                ('id_card', models.CharField(max_length=50, null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('checkin_date', models.DateTimeField(null=True)),
                ('checkout_date', models.DateTimeField(null=True)),
                ('imgset_dir', models.CharField(max_length=200, null=True)),
                ('profile_photo', models.CharField(max_length=200, null=True)),
                ('DESCRIPTION', models.CharField(max_length=200, null=True)),
                ('ISACTIVE', models.CharField(max_length=10, null=True)),
                ('CREATED', models.DateTimeField(null=True)),
                ('CREATEBY', models.IntegerField(null=True)),
                ('UPDATED', models.DateTimeField(null=True)),
                ('UPDATEBY', models.IntegerField(null=True)),
                ('REMOVE', models.CharField(max_length=1, null=True)),
            ],
            options={
                'db_table': 'volunteer_info',
            },
        ),
    ]
