# Generated by Django 4.2.2 on 2023-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OldPersonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=50)),
                ('id_card', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField()),
                ('checkin_date', models.DateTimeField()),
                ('checkout_date', models.DateTimeField()),
                ('imgset_dir', models.CharField(max_length=200)),
                ('profile_photo', models.CharField(max_length=200)),
                ('room_number', models.CharField(max_length=50)),
                ('firstguardian_name', models.CharField(max_length=50)),
                ('firstguardian_relationship', models.CharField(max_length=50)),
                ('firstguardian_phone', models.CharField(max_length=50)),
                ('firstguardian_wechat', models.CharField(max_length=50)),
                ('secondguardian_name', models.CharField(max_length=50)),
                ('secondguardian_relationship', models.CharField(max_length=50)),
                ('secondguardian_phone', models.CharField(max_length=50)),
                ('secondguardian_wechat', models.CharField(max_length=50)),
                ('health_state', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('is_active', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('update_by', models.IntegerField()),
                ('remove', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'oldperson_info',
            },
        ),
    ]
