# Generated by Django 4.2.2 on 2023-07-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldperson_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldpersoninfo',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldpersoninfo',
            name='checkout_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldpersoninfo',
            name='CREATED',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldpersoninfo',
            name='UPDATED',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldpersoninfo',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
