# Generated by Django 4.2.2 on 2023-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(blank=True, null=True, verbose_name='事件类型')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='事件日期')),
                ('event_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='事件地点')),
                ('event_desc', models.CharField(blank=True, max_length=200, null=True, verbose_name='事件描述')),
                ('oldperson_id', models.IntegerField(blank=True, null=True, verbose_name='老人ID')),
            ],
            options={
                'db_table': 'event_info',
            },
        ),
    ]
