# Generated by Django 4.2.2 on 2023-07-05 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='CREATED',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='UPDATED',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='hire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeinfo',
            name='resign_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
