# Generated by Django 4.2.2 on 2023-07-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ORG_ID', models.IntegerField()),
                ('CLIENT_ID', models.IntegerField()),
                ('UserName', models.CharField(max_length=50, verbose_name='用户名')),
                ('Password', models.CharField(blank=True, max_length=50, null=True, verbose_name='密码')),
                ('REAL_NAME', models.CharField(blank=True, max_length=50, null=True)),
                ('SEX', models.CharField(blank=True, max_length=20, null=True)),
                ('EMAIL', models.CharField(blank=True, max_length=50, null=True)),
                ('PHONE', models.CharField(blank=True, max_length=50, null=True)),
                ('MOBILE', models.CharField(blank=True, max_length=50, null=True)),
                ('DESCRIPTION', models.CharField(blank=True, max_length=200, null=True)),
                ('ISACTIVE', models.CharField(blank=True, max_length=10, null=True)),
                ('CREATED', models.DateTimeField(blank=True, null=True)),
                ('CREATEBY', models.IntegerField(blank=True, null=True)),
                ('UPDATED', models.DateTimeField(blank=True, null=True)),
                ('UPDATEBY', models.IntegerField(blank=True, null=True)),
                ('REMOVE', models.CharField(blank=True, max_length=1, null=True)),
                ('DATAFILTER', models.CharField(blank=True, max_length=200, null=True)),
                ('theme', models.CharField(blank=True, max_length=45, null=True)),
                ('defaultpage', models.CharField(blank=True, max_length=45, null=True, verbose_name='登录成功页面')),
                ('logoimage', models.CharField(blank=True, max_length=45, null=True, verbose_name='显示不同logo')),
                ('qqopenid', models.CharField(blank=True, max_length=100, null=True, verbose_name='第三方登录的凭证')),
                ('appversion', models.CharField(blank=True, max_length=10, null=True, verbose_name='检测app的版本号')),
                ('jsonauth', models.CharField(blank=True, max_length=1000, null=True, verbose_name='app权限控制')),
            ],
        ),
    ]
