# Generated by Django 4.2.2 on 2023-07-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sys_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sysuser',
            table='sys_user',
        ),
    ]
